package com.bawei.ssm.user.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bawei.ssm.user.model.User;
import com.bawei.ssm.user.model.UserExample;
import com.bawei.ssm.user.model.UserForm;

public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	User selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	int updateByExample(@Param("record") User record, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	int updateByPrimaryKey(User record);

	/**
	 * @author liuzeke
	 * @date 2017年8月22日
	 * @time 下午2:56:34
	 * @return
	 */
	List<UserForm> getUserForm();
}