package com.bawei.ssm.reroleresource.model;

public class RelationRoleResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_role_resource.id
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_role_resource.role_id
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_role_resource.resource_id
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    private Long resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_role_resource.id
     *
     * @return the value of re_role_resource.id
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_role_resource.id
     *
     * @param id the value for re_role_resource.id
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_role_resource.role_id
     *
     * @return the value of re_role_resource.role_id
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_role_resource.role_id
     *
     * @param roleId the value for re_role_resource.role_id
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_role_resource.resource_id
     *
     * @return the value of re_role_resource.resource_id
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_role_resource.resource_id
     *
     * @param resourceId the value for re_role_resource.resource_id
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }
}