package com.bawei.ssm.reroleresource.mapper;

import com.bawei.ssm.reroleresource.model.RelationRoleResource;
import com.bawei.ssm.reroleresource.model.RelationRoleResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    long countByExample(RelationRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    int deleteByExample(RelationRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    int insert(RelationRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    int insertSelective(RelationRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    List<RelationRoleResource> selectByExample(RelationRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    RelationRoleResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") RelationRoleResource record, @Param("example") RelationRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    int updateByExample(@Param("record") RelationRoleResource record, @Param("example") RelationRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    int updateByPrimaryKeySelective(RelationRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_role_resource
     *
     * @mbg.generated Tue Aug 22 13:57:51 CST 2017
     */
    int updateByPrimaryKey(RelationRoleResource record);
}