package com.bawei.ssm.reuserrole.mapper;

import com.bawei.ssm.reuserrole.model.RelationUserRole;
import com.bawei.ssm.reuserrole.model.RelationUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    long countByExample(RelationUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    int deleteByExample(RelationUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    int insert(RelationUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    int insertSelective(RelationUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    List<RelationUserRole> selectByExample(RelationUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    RelationUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") RelationUserRole record, @Param("example") RelationUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    int updateByExample(@Param("record") RelationUserRole record, @Param("example") RelationUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    int updateByPrimaryKeySelective(RelationUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_user_role
     *
     * @mbg.generated Tue Aug 22 13:56:54 CST 2017
     */
    int updateByPrimaryKey(RelationUserRole record);
}