package com.bawei.ssm.user.model;

import java.io.Serializable;

public class User implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.id
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	private Long id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.username
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	private String username;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.name
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.id
	 *
	 * @return the value of user.id
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.id
	 *
	 * @param id
	 *            the value for user.id
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.username
	 *
	 * @return the value of user.username
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.username
	 *
	 * @param username
	 *            the value for user.username
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.name
	 *
	 * @return the value of user.name
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.name
	 *
	 * @param name
	 *            the value for user.name
	 *
	 * @mbg.generated Thu Aug 17 09:40:04 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}